name: zSchedulers
author: Maxlego08
main: fr.maxlego08.zscheduler.SchedulerPlugin
website: https://groupez.dev
description: Scheduler plugin
version: 1.0.0
api-version: 1.13
depend:
  - PlaceholderAPI
commands: